### ISSUE TITLE
Crear contolador Registro y validaciones del formulario Jefe de Familia

### ISSUE THREAD

**Issue by ViT4RGh0ST** [ViT4RGh0ST/Management-System-Clap-backend#1]
- [ ] Crear Controlador de Registro
- [ ] Crear validaciones de los campos respectivos basándote en la tabla de migración de jefe de familia

No te preocupes por los arrays eso lo resolvemos al rato (se usan al momento de especificar varios elementos del mismo tipo, animales plaga, objetos, mascotas, miembros de familia etc)

**Comment by ViT4RGh0ST** [comment]
Ah yuli, crea el controlador sin resource, crealo generico para mejor control de rutas

**Comment by yuliannycm** [comment]
ok, lo que te decía, creo que estoy fastidiosa con el tema pero sigo con esa duda: recuerdas cuando te envié la imagen de la vista donde salia el nombre de cada campo verdad? me dijiste que si van a ser arreglos, en el caso de nombres y apellidos, hasta donde vi esos mismos son los que van en el controlador, pero hasta ahora yo solo he trabajado con variables normalitas, no de tipo arreglo y es ahí donde no se que hacer...

**Comment by ViT4RGh0ST** [comment]
Monta un capture 👍 
![image](https://user-images.githubusercontent.com/19257351/38705932-55dfafce-3e79-11e8-83e4-c9ec80f4bc04.png)

**Comment by ViT4RGh0ST** [comment]
Como te comentaba en el issue trabaja con la informacion de la migracion de jefe familiar
recuerda que primero se registra él, y cuando este dentro del sistema (logueado) va a poder registrar miembros familiares, te cuento, la etiqueta name no la necesita el frontend(o no deberia), esa la usamos nosotros para el backend
Y ahi es donde usaremos arreglos, aunque, antes tambien en la fase de registro de hogar XD
pero eso es despues, no es importante ahora no para este issue

**Comment by yuliannycm** [comment]
subí las validaciones, coloque  los mensajes de error para ver si las validaciones funcionaban como debían (aunque se ve horrible xd)
